# Generated by Django 3.0.1 on 2020-01-02 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=64)),
                ('phase_total', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('survey_done', models.BooleanField()),
                ('survey_report_received', models.BooleanField()),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLACE_ID', models.CharField(max_length=50)),
                ('EFF_STARTDATE', models.DateTimeField()),
                ('EFF_ENDDATE', models.DateTimeField()),
                ('LEVEL', models.IntegerField()),
                ('TITLE', models.CharField(max_length=60)),
                ('ISO_2_CODE', models.CharField(max_length=2)),
                ('ISO_3_CODE', models.CharField(max_length=3)),
                ('ADM0_NAME', models.CharField(max_length=100)),
                ('ADM1_NAME', models.CharField(max_length=100)),
                ('ADM2_NAME', models.CharField(max_length=100)),
                ('ADM0_TITLE', models.CharField(max_length=100)),
                ('ADM1_TITLE', models.CharField(max_length=100)),
                ('ADM2_TITLE', models.CharField(max_length=100)),
                ('WHO_REGION', models.CharField(max_length=30)),
                ('UNICEF_REG', models.CharField(max_length=30)),
                ('SHAPE_WHO_GUID', models.CharField(max_length=50)),
                ('CENTER_LON', models.CharField(max_length=30)),
                ('CENTER_LAT', models.CharField(max_length=30)),
                ('IS_CURRENT', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso3', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=50)),
                ('WHO_region', models.CharField(max_length=20, null=True)),
                ('UNICEF_region', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extent', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_text', models.CharField(blank=True, max_length=150)),
                ('phase_no', models.IntegerField()),
                ('tr_received', models.BooleanField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='SIA.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Target_population_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='YesNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yesno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_other', models.CharField(max_length=255)),
                ('target_age_other', models.CharField(max_length=50)),
                ('target_population', models.IntegerField()),
                ('population_reached', models.IntegerField()),
                ('admin_coverage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('survey_coverage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('admin2', models.ManyToManyField(blank=True, related_name='sub_activities', to='SIA.Area')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_activities', to='SIA.Intervention')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_activities', to='SIA.Phase')),
                ('target_age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_activities', to='SIA.Age')),
                ('target_population_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_activities', to='SIA.Target_population_source')),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='phase_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases', to='SIA.Status'),
        ),
        migrations.AddField(
            model_name='age',
            name='intervention',
            field=models.ManyToManyField(blank=True, related_name='age', to='SIA.Intervention'),
        ),
        migrations.CreateModel(
            name='Activity_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=30)),
                ('intervention', models.ManyToManyField(blank=True, related_name='activity_types', to='SIA.Intervention')),
            ],
        ),
        migrations.CreateModel(
            name='Activity_intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_interventions', to='SIA.Activity')),
                ('activity_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_interventions', to='SIA.Status')),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_interventions', to='SIA.Activity_type')),
                ('extent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_interventions', to='SIA.Extent')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_interventions', to='SIA.Intervention')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='SIA.Country'),
        ),
        migrations.AddField(
            model_name='activity',
            name='phased_yesno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='SIA.YesNo'),
        ),
    ]
