# Generated by Django 3.0.1 on 2020-01-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_type',
            name='definition',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='activity_type',
            name='standard_age_group',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
